apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sre-microservices
type: Opaque
stringData:
  POSTGRES_USER: cloudacademy
  POSTGRES_PASSWORD: pfm_2020
  USER_DB_URL: "postgresql://cloudacademy:pfm_2020@user-db:5432/user"
  PRODUCT_DB_URL: "postgresql://cloudacademy:pfm_2020@product-db:5432/product"
  ORDER_DB_URL: "postgresql://cloudacademy:pfm_2020@order-db:5432/orders"
  NOTIFICATION_DB_URL: "postgresql://cloudacademy:pfm_2020@notification-db:5432/notifications"
  PAYMENT_DB_URL: "postgresql://cloudacademy:pfm_2020@payment-db:5432/payments"
